on: [push] # 保存ボタンが押されたらスタート
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Test (検品実行)
        run: node test.js

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # 第3章で作った鍵を使う
      
      - name: Get secret from Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "taro-kv-handson2" # 作成したKey Vault名
          secrets: "taro-PASSWORD"    # 作成したシークレット名
        id: kv-step

      - name: Check Secret
        run: echo "金庫から取り出した値は ${{ steps.kv-step.outputs.taro-PASSWORD }} です"
      
      - name: Deploy Infrastructure (Bicep)
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: 'taro-rg-handson-cicd'
          template: ./main.bicep

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taro-webapp-cicd2'
